export const DATA = {
  userName: 'LongUserName',
  rating: 5,
  balance: '$100,500.00',
  progress: 70,
  avatar: '/src/assets/images/avatar.png',
  tournaments: [
    {
      id: 1,
      status: 'registering',
      NL: 'NL 2-7 Triple Draw',
      name: 'OFC Pineapple',
      date: '12:00 pm, 28 July',
      countPlayers: 1000,
      countAllPlayers: 1000,
      points: 1000000,
    },
    {
      id: 2,
      status: 'registering',
      NL: 'NL Holdem',
      name: 'OFC Pineapple',
      date: '12:00 pm, 28 July',
      countPlayers: 1,
      countAllPlayers: 6,
      points: 100,
    },
    {
      id: 3,
      status: 'cancelled',
      NL: 'NL OFC/pineapple prg',
      name: 'Hourly Freeroll',
      date: '12:00 pm, 28 July',
      countPlayers: 1,
      countAllPlayers: 10000,
      points: 1000,
      isTime: true,
      isFreeRoll: true,
    },
    {
      id: 4,
      status: 'cancelled',
      NL: 'NL 2-7 Triple Draw',
      name: 'OFC Pineapple',
      date: '12:00 pm, 28 July',
      countPlayers: 1000,
      countAllPlayers: 1000,
      points: 1000000,
    },
    {
      id: 5,
      status: 'cancelled',
      NL: 'NL 2-7 Triple Draw',
      name: 'OFC Pineapple',
      date: '12:00 pm, 28 July',
      countPlayers: 0,
      countAllPlayers: 100,
      points: 146,
      isRapid: true,
    },
    {
      id: 6,
      status: 'registering',
      NL: 'NL 2-7 Triple Draw',
      name: 'OFC Pineapple',
      date: '12:00 pm, 28 July',
      countPlayers: 1000,
      countAllPlayers: 1000,
      points: 1000000,
    },
  ]
}



